from pathlib import Path


TRAIN_ROOT = Path(r"C:\Users\User\Pictures\train")
BLOG_ROOT = Path(r"C:\www\blog")
BLOG_ENV_PATH = BLOG_ROOT / ".env"
BLOG_PUBLIC_STORAGE_ROOT = BLOG_ROOT / "storage" / "app" / "public"

# 直接改這裡就能換掃描根目錄。
VIDEO_ROOTS = [
    {
        "label": "FC2 精選",
        "path": Path(r"Z:\FC2-2026(new)\精選"),
    },
]

VIDEO_EXTENSIONS = {
    ".mp4",
    ".mkv",
    ".avi",
    ".mov",
    ".wmv",
    ".ts",
    ".m4v",
}

FEATURE_MODEL = "facenet_pytorch_vggface2_mtcnn_v1"
FRAME_INTERVAL_SECONDS = 1
FIRST_SAMPLE_OFFSET_SECONDS = 0
NEARBY_FRAME_OFFSETS_SECONDS = (0,)
SECONDS_TO_SKIP_AFTER_SUCCESS = 20
MAX_SAMPLES_PER_VIDEO = 20
MAX_FRAME_CHECKS_PER_VIDEO = 7200
SKIP_COMPLETED_VIDEOS = True
SKIP_LOCKED_VIDEOS = True

MTCNN_IMAGE_SIZE = 160
MTCNN_MARGIN = 14
MTCNN_MIN_FACE_SIZE = 72

MIN_DETECTION_PROBABILITY = 0.86
MIN_FACE_WIDTH = 120
MIN_FACE_HEIGHT = 120
MIN_BLUR_SCORE = 30.0
MIN_BRIGHTNESS = 50.0
MIN_LOWER_FACE_STD = 16.0
MIN_LOWER_FACE_TEXTURE = 14.0
MAX_EYE_ANGLE_DEGREES = 18.0
MAX_NOSE_OFFSET_RATIO = 0.26
MAX_MOUTH_OFFSET_RATIO = 0.34
HARD_MAX_EYE_ANGLE_DEGREES = 22.0
HARD_MAX_NOSE_OFFSET_RATIO = 0.34
HARD_MAX_MOUTH_OFFSET_RATIO = 0.42
HARD_MAX_VERTICAL_RATIO = 1.90
MIN_VERTICAL_RATIO = 0.62
MAX_VERTICAL_RATIO = 1.34
MIN_FRONT_SCORE = 0.34
CROP_MARGIN_RATIO = 0.26

VIDEO_CLUSTER_MATCH_THRESHOLD = 0.73
PERSON_MATCH_THRESHOLD = 0.78

SAMPLE_IMAGE_SUBDIR = "face-identity/samples"
LOG_PATH = TRAIN_ROOT / "logs" / "face_identity_scan.log"
DEBUG_FRAME_LOG_LIMIT = 220
DEBUG_METADATA_EVENT_LIMIT = 120
